version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    env_file: ./.env
    ports:
      - "3040:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: BSL
